### ISSUE TITLE
Use of Hook.useRef

### ISSUE THREAD

**Issue by francotiveron** [fable-compiler/Fable.Lit#68]
In https://fable.io/Fable.Lit/docs/hook-components.html the first example shows the use of Hook.useRef:

```
open Lit

[<HookComponent>]
let NameInput() =
    let value, setValue = Hook.useState "World"
    let inputRef = Hook.useRef<HTMLInputElement>()

    html $"""
      <div class="content">
        <p>Hello {value}!</p>
        <input {Ref inputRef}
          value={value}
          @keyup={EvVal setValue}
          @focus={Ev(fun _ -> inputRef.Value |> Option.iter (fun el -> el.select()))}>
      </div>
    """
```

1 - In the row '<input {Ref inputRef}', where is the symbol 'Ref' defined? It doesn't seem to exist
2 - Is there a complete example/demo where we can see how useRef is intended to be used?

**Comment by alfonsogarciacaro** [comment]
Ups, sorry. At the end we used `Lit.refValue` and `Lit.refCallback` instead of `Ref` to help the type checker but forgot to update the docs 😅 

`useRef` is very similar to the [React hook with the same name](https://reactjs.org/docs/hooks-reference.html#useref). You can see [a usage example in Lit.TodoMVC](https://github.com/alfonsogarciacaro/Lit.TodoMVC/blob/d7e56a62ba001c20470c3e8e0d1e5f461b18be3e/src/Todos.fs#L93).
